### ISSUE TITLE
Sort exact-times timetables by departure time

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/r5#568] opened 2020-01-06 04:33 UTC
A user has reported a bug related to add-trip modifications with multiple exact-times timetables.

 ## Expected behavior ##
For a simple add-trip modification with two exact-times timetables running every 30 minutes:
- Timetable 1, active only on Monday, from 7:01 to 8:30.
- Timetable 2, active all days of week, from 12:01 to 13:30.

Departing Monday between 7:00 and 8:00 ✔️:
![image](https://user-images.githubusercontent.com/2173529/71794670-8eb41d00-3010-11ea-95d0-5ac4670884a5.png)

Departing Monday between 12:00 and 13:00 ✔️:
![image](https://user-images.githubusercontent.com/2173529/71794692-b5725380-3010-11ea-8ec8-1ae685739465.png)

Departing Tuesday between 7:00 and 8:00 (service should be inactive) ✔️ :
![image](https://user-images.githubusercontent.com/2173529/71794739-e5b9f200-3010-11ea-8871-a77cb4528f1f.png)

Departing Tuesday between 12:00 and 13:00 ✔️:
![image](https://user-images.githubusercontent.com/2173529/71794780-0bdf9200-3011-11ea-8018-1cb2c8a1a601.png)

## Unexpected behavior ##
Similar to above, except timetables are replaced by:
- Timetable 3, active only on Monday from 12:01 to 13:30
- Timetable 4, active all days of week, from 7:01 to 8:30

Departing Monday between 7:00 and 8:00 (**service should be provided by Timetable 4** ❌ ):
![image](https://user-images.githubusercontent.com/2173529/71794987-020a5e80-3012-11ea-9056-5bfa26b1f3ce.png)

Departing Monday between 12:00 and 13:00 ✔️ :
![image](https://user-images.githubusercontent.com/2173529/71795022-1cdcd300-3012-11ea-9707-ccbb1aa48519.png)

Departing Tuesday between 7:00 and 8:00 ✔️ :
![image](https://user-images.githubusercontent.com/2173529/71795045-3b42ce80-3012-11ea-88a5-c7865ad942dc.png)

Departing Tuesday between 12:00 and 13:00 (service inactive ✔️ ):
![image](https://user-images.githubusercontent.com/2173529/71795142-bf955180-3012-11ea-9c5c-66702015d521.png)

## Troubleshooting ##
There's a concerning TODO at https://github.com/conveyal/r5/blob/4ccd24172985bb8254ff35b11a7a59f2cc192f2e/src/main/java/com/conveyal/r5/transit/TripSchedule.java#L123
but does that just refer to sanity-checking for exact-times?

**Comment by ansoncfit** [comment] 2020-01-06 05:06
Ah, FastRaptorWorker assumes trips are sorted by departure time -- the TODO above probably includes sorting the trips by departure time.

https://github.com/conveyal/r5/blob/4ccd24172985bb8254ff35b11a7a59f2cc192f2e/src/main/java/com/conveyal/r5/profile/FastRaptorWorker.java#L544

Debugging the second example above confirms that trips' `arrivals` and `departures` are currently ordered according to the frequency entry, not according to time!

**Comment by abyrd** [comment] 2020-01-06 08:58
Thanks for the thorough write-up and links to specific lines @ansoncfit. 

When building a TransitLayer from GTFS, R5 doesn't handle exact_times=1 at all. There is a provision for exact_times like behavior in R5 AddTrips modifications via the firstDepartures field of PatternTimetable. Each AddTrips has a `Collection<PatternTimetable> frequencies`, and each PatternTimetable has an array firstDepartures, which when present effectively means exact_times = true on that particular timetable.

However, there is no Javadoc stating that the `Collection<PatternTimetable>` is required to be ordered, nor that the `firstDepartures` within each PatternTimetable are required to be ordered. We do happen to always generate increasing `firstDepartures`, but it's possible for someone to supply out-of-order timetables. When the `firstDepartures` from all the timetables are merged, there is no check that they are sorted as required by the routing algorithm.

Partial expansion of "exact times" timetables happens when converting UI/Mongo/Backend modifications to R5 modifications, in `com.conveyal.taui.models.AbstractTimetable#toBaseR5Timetable`. This creates a series of increasing departure times in the `firstDepartures` fields.

I have added Javadoc clarifying the expectations about ordering, and added some code to enforce/fix the ordering.

**Comment by ansoncfit** [comment] 2020-01-06 13:28
> When building a TransitLayer from GTFS, R5 doesn't handle exact_times=1 at all.

Do our user manual and javadoc clearly explain this? Are trips in input GTFS with exact_times = 1 ignored, or treated as inexact frequency entries?

**Comment by abyrd** [comment] 2020-01-07 08:33
> > When building a TransitLayer from GTFS, R5 doesn't handle exact_times=1 at all.
> 
> Do our user manual and javadoc clearly explain this? Are trips in input GTFS with exact_times = 1 ignored, or treated as inexact frequency entries?

They are not ignored, it looks like they are treated as "pure" unscheduled frequencies. A warning is logged, but that won't be bubbled up to the analysis web UI. This behavior remains from R5's early use as a point to point routing engine, where the build log would be more visible and the schedule / pure frequency distinction was not yet so significant.

We should make it skip these exact_times frequencies entirely, or probably even fail hard to indicate the input will not yield 100% valid output. I will have it throw an exception until we have a better fix. I would prefer to reuse the same frequency expansion code for both GTFS and AddTrips, but they're happening in very different places.

**Comment by ansoncfit** [comment] 2020-01-07 14:38
I'm not in favor of a hard failure that would break existing functionality (even if it leads to inaccurate results) by preventing any use of feeds with exact_times = 1. For example, the Santiago feed we've been using has two lines with exact_times = 1 (we'll want to revise that section of the paper we just drafted...)

I can add a note in the user manual explaining that until we have the longer-term solution, exact_times frequency trips will be treated as "pure" frequency trips (or, if you think we should definitely keep the hard failure, that feeds with such trips are not supported).

**Comment by Nate-Wessel** [comment] 2020-01-11 16:15
I was able to reproduce this bug with v4.7.0. 
The fix in v4.7.1-127-ge1b96f7 seems to correct it.

**Closed** 2020-04-09 03:33 UTC
Labels: bug
