### ISSUE TITLE
Can SQS queue get clogged?

### ISSUE THREAD

**Issue by abyrd** [conveyal/r5#322] opened 2017-08-14 11:12 UTC
What happens if the SQS results queue has messages in it, then the backend is restarted? What will be done with the queue messages that no longer correspond to any known regional analysis?

**Comment by ansoncfit** [comment] 2017-10-03 04:27
One thing that seems to happen is that the restarted backend will choke trying to spit out the warning here:

https://github.com/conveyal/r5/blob/master/src/main/java/com/conveyal/r5/analyst/cluster/GridResultQueueConsumer.java#L63

Using the "Purge Queue" action in SQS may help avoid this.  Also, silencing that warning.

**Comment by mattwigway** [comment] 2017-11-28 05:51
I could have sworn I'd already disabled that warning. Removing it should be all that needs to happen.

**Comment by ansoncfit** [comment] 2017-12-22 21:27
The backend chokes printing this log warning when a regional job that is running is deleted, not just when the broker is restarted.  I just saw it take more than 2 minutes to log the complaint that it was discarding completed work for ~100k origins.  Memory usage spiked to over 3 gigs.  If the memory spike was indeed caused by dealing with deleting this 1 regional analysis, deleting 3 regional analyses could easily overwhelm the backend.

The assembly of results of other running regional analyses also seems to have stalled out for about 10 minutes before continuing apace and catching up with the results that workers had finished.

**Comment by abyrd** [comment] 2017-12-22 22:19
@ansoncfit those observations are not entirely unexpected. When a job is deleted, there will be tasks in flight (roughly nWorkers * nCores * 2 tasks). The results for those tasks will end up in the queue and will be received by the backend, which will see that there is no result assembler to drop them into. But do you mean it printed this message 100k times? That would imply that the job was never actually deleted, and that 100k results were hanging around in the queue. 

It's also tricky to estimate whether memory usage is really increasing in Java. If you tell the JVM it can use 18 GB of memory, it may well decide to use 18GB of memory when it doesn't strictly need to - it may just pile up objects and not garbage collect unused ones because you told it it was OK to use up to 18GB of memory.

If assembly stalls though, I'd rapidly suspect the IOPS limits. I did fix the problem where it fills a multi-GB file with zeros every time you create a new analysis, but I'm not sure if that change is on production.

**Comment by abyrd** [comment] 2017-12-22 22:23
Looks like my filling-with-zeros fix is in dev but not in master (commit `2e49f8c79a698389390e8ff8255f0644fa8af21b`).

**Comment by ansoncfit** [comment] 2017-12-22 22:34
The message was printed many thousands of times.  I think the workers did stop working on the deleted job, but they were far ahead of the result compiler.

**Comment by ansoncfit** [comment] 2017-12-22 22:51
@abyrd and it's analysis-backend that does the filling with zeroes (via a dependency on R5), right?  So if the pom of analysis-backend is pegged to a snapshot release of R5 from early November, it won't take advantage of the fix?

**Comment by abyrd** [comment] 2017-12-24 19:46
Right @ansoncfit, if analysis-backend is not depending on R5 including that commit cited above, it does not have the fix. On the other hand that file will only be big if the workers are computing a lot of bootstrap replications of accessibility. That would also depend on the worker version.

**Comment by ansoncfit** [comment] 2018-02-07 17:17
Fixed in https://github.com/conveyal/r5/pull/399

**Closed by ansoncfit** 2018-02-07 17:17 UTC
Labels: high priority
